# Generated by Django 3.1 on 2022-06-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='users',
            new_name='user',
        ),
    ]
