# Generated by Django 3.1 on 2022-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220615_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
