# Generated by Django 3.1 on 2022-06-21 06:25

import account.models
from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Test with 1 answer'), ('2', 'Test with many answers'), ('3', 'Translate word/phrase')], default='1', max_length=1)),
                ('answer', models.CharField(max_length=500)),
                ('variants', models.CharField(max_length=15)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='Lorem ipsum')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_tests', to='edu.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=materials.models.upload_video)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('lesson', models.ManyToManyField(related_name='video_material_for_lesson', to='edu.Lessons')),
                ('task', models.ManyToManyField(related_name='video_material_for_task', to='materials.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=account.models.upload_image)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('lesson', models.ManyToManyField(related_name='image_material_for_lesson', to='edu.Lessons')),
                ('task', models.ManyToManyField(related_name='image_material_for_task', to='materials.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to=materials.models.upload_audio)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('lesson', models.ManyToManyField(related_name='audio_material_for_lesson', to='edu.Lessons')),
                ('task', models.ManyToManyField(related_name='audio_material_for_tasks', to='materials.Tasks')),
            ],
        ),
    ]
