# Generated by Django 3.1 on 2022-06-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
