# Generated by Django 3.1 on 2022-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20220615_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='text',
            field=models.TextField(default='Lorem ipsum'),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
