# Generated by Django 3.1 on 2022-06-18 20:52

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(unique=True)),
                ('preview', models.ImageField(upload_to=account.models.upload_image)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('1', 'Text'), ('2', 'Audio'), ('3', 'Video'), ('4', 'Image')], default='1', max_length=1)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='Lorem ipsum')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu.courses')),
            ],
        ),
        migrations.CreateModel(
            name='User2Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_finished', models.BooleanField(default=False)),
                ('min_percent', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('course_tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.courses')),
                ('user_tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_for_lesson', to='edu.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(through='edu.User2Course', to=settings.AUTH_USER_MODEL),
        ),
    ]
