# Generated by Django 3.1 on 2022-06-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='lesson_tb',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='user_tb',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='theme',
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edu.courses'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='text',
            field=models.TextField(default='Lorem ipsum'),
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
